# Generated by Django 2.0.5 on 2021-02-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_product1',
            old_name='send_to',
            new_name='designation',
        ),
    ]
