# Generated by Django 2.0.5 on 2021-02-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_director', '0002_auto_20210215_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_product1',
            name='fcontent',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
