# Generated by Django 2.0.5 on 2021-02-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_director', '0003_upload_product1_fcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_product1',
            name='fcontent',
            field=models.TextField(),
        ),
    ]
