# Generated by Django 2.0.5 on 2021-01-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
