# Generated by Django 2.0.5 on 2021-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210213_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_reg',
            name='group_password1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
