# Generated by Django 2.0.5 on 2021-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_reg_group_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='dkey_request1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=300)),
                ('empname', models.CharField(max_length=300)),
                ('empemail', models.CharField(max_length=300)),
                ('emp_designation', models.CharField(max_length=300)),
                ('fileid', models.CharField(max_length=300)),
                ('stauts', models.CharField(max_length=300)),
                ('dkey', models.CharField(max_length=200)),
            ],
        ),
    ]
