# Generated by Django 2.0.5 on 2021-02-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_dkey_request1'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=300)),
                ('payment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='transportation1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_no', models.CharField(max_length=300)),
                ('project_name', models.CharField(max_length=300)),
                ('send_place', models.CharField(max_length=300)),
            ],
        ),
    ]
